name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run detekt
      run: ./gradlew detekt

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
    - name: Upload SARIF to GitHub using the upload-sarif action
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: detekt.sarif
